### ISSUE TITLE
Data generator should write to gDrive when regenerating data

### ISSUE THREAD

**Issue by j-barber** [galatea-associates/kafka-poc#76] opened 2018-12-07 13:54 UTC

**Comment by Gala-Sortino** [comment] 2018-12-07 13:57
Copy of issue #46

**Comment by j-barber** [comment] 2018-12-07 14:07
Closed as duplicate of #46

**Comment by Gala-Sortino** [comment] 2018-12-11 14:16
Closed as duplicate of #46

**Closed as completed by Gala-Sortino** 2018-12-11 14:16 UTC
